// Generated by CoffeeScript 1.6.3
var Index;

(require('source-map-support')).install({
  handleUncaughtExceptions: false
});

module.exports = new (Index = (function() {
  function Index() {}

  Index.prototype.polvo = true;

  Index.prototype.type = 'style';

  Index.prototype.name = 'css';

  Index.prototype.output = 'css';

  Index.prototype.ext = /\.css$/m;

  Index.prototype.exts = ['.css'];

  Index.prototype.compile = function(filepath, source, debug, error, done) {
    return done(source, null);
  };

  return Index;

})());
