// Generated by CoffeeScript 1.6.3
var Index, clone, fs, path;

(require('source-map-support')).install({
  handleUncaughtExceptions: false
});

path = require('path');

fs = require('fs');

clone = require('regexp-clone');

module.exports = new (Index = (function() {
  var has_imports, match_all;

  function Index() {}

  Index.prototype.type = 'style';

  Index.prototype.name = 'css';

  Index.prototype.output = 'css';

  Index.prototype.ext = /\.css$/m;

  Index.prototype.exts = ['.css'];

  Index.prototype.partials = true;

  has_imports = /^(?:(?!\s*\/\*).?)\@import/gm;

  match_all = /^(?:(?!\s*\/\*).?)\@import\s*(?:url\s*\(\s*)?(?:'|")([^'"]+)(?:'|")\s*\)?\s*;?/gm;

  Index.prototype.is_partial = function(filepath) {
    return /^_/m.test(path.basename(filepath));
  };

  Index.prototype.compile = function(filepath, source, debug, error, done) {
    return done(this.render_partials(filepath, source, error), null);
  };

  Index.prototype.resolve_dependents = function(filepath, files) {
    var all, dependents, dirpath, each, has, iimport, match, name, sub, _i, _len, _ref;
    dependents = [];
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      each = files[_i];
      _ref = [clone(has_imports), clone(match_all)], has = _ref[0], all = _ref[1];
      if (!has.test(each.raw)) {
        continue;
      }
      dirpath = path.dirname(each.filepath);
      name = path.basename(each.filepath);
      while ((match = all.exec(each.raw)) != null) {
        iimport = match[1];
        iimport = iimport.replace(/\.css$/m, '') + '.css';
        iimport = path.join(dirpath, iimport);
        if (iimport === filepath) {
          if (!this.is_partial(name)) {
            dependents.push(each);
          } else {
            sub = this.resolve_dependents(each.filepath, files);
            dependents = dependents.concat(sub);
          }
        }
      }
    }
    return dependents;
  };

  Index.prototype.render_partials = function(filepath, source, error) {
    var all, buffer, full, has, iimport, iimport_path, match, partial_content, _ref;
    _ref = [clone(has_imports), clone(match_all)], has = _ref[0], all = _ref[1];
    if (!has.test(source)) {
      return source;
    }
    buffer = source;
    while ((match = all.exec(source)) != null) {
      full = match[0];
      iimport = match[1];
      iimport_path = path.join(path.dirname(filepath), iimport);
      iimport_path = iimport_path.replace(/\.css$/m, '') + '.css';
      if (fs.existsSync(iimport_path)) {
        partial_content = fs.readFileSync(iimport_path).toString();
        partial_content = this.render_partials(iimport_path, partial_content, error);
      } else {
        partial_content = '';
        error("file '" + iimport + "' do not exist for '" + filepath + "'");
      }
      buffer = buffer.replace(full, partial_content);
    }
    return buffer;
  };

  return Index;

})());
